### ISSUE TITLE
Offline installation Cosmos DB ADS Extension is not working

### ISSUE THREAD

**Issue by SachinSACCSaxo** [Azure/azure-cosmosdb-ads-extension#117]
Hi,

We wanted to do offline installation of Cosmos DB ADS Extension in Azure Data Studio in a secure environment.

For some reason the Cosmos DB ADS Extension does not activate when starting Azure Data Studio in a System context. 
It seems to be trying to connect to the IP address: **68.232.34.200:433** which makes no sense given that the installation was done offline through SCCM. 

We would like to have it installed in a locked environment with no external communication. That's why we call it offline installation.

![image](https://github.com/user-attachments/assets/0896b97f-646d-464e-871b-28453244d4de)

![image](https://github.com/user-attachments/assets/571d5bf1-4a7f-48dd-a5ae-7cc94a3ecaee)

Another strange thing is that even if the extension is not activated, we can still see the extension controls in the UI. But when trying to connect to Database it just hangs for forever.

![image](https://github.com/user-attachments/assets/04def5ed-a585-41ae-8453-b025e367972f)

**Comment by ignacioleonr** [comment]
Tagging @languy to help triage and investigate the issue.

**Comment by languy** [comment]
To summarize the findings.
* ADS was installed using the "System" version through command line under the admin user on Windows.
* The .NET and Cosmos DB extensions were installed using the `.vsix` file from the command line under the admin user
The idea was to pre-install ADS and its extensions so users don't have to do it.

There were multiple issues:
1. When the user uses the extensions for the first time, the .NET extension downloads the .NET runtime in the extension folder which will fail, because the extension was installed by the admin user in a folder created by admin and where the user doesn't have write permissions. For now, the workaround was to pre-download and install the runtime in the extension folder by the admin, so that the user wouldn't have to do it.
2. The Cosmos DB extension version `0.4.5` also downloads the Mongo Shell and sample data which will trigger the same permission problem. We have released version `0.4.6` which fixes the issue.
3. The extensions are not self-contained and must still download the binaries, so currently the network configuration must allow ADS to make remote calls to fetch the binaries.
